# Main configuration file for Nuclei AI Agent Template Generator
app:
  name: "Nuclei AI Agent Template Generator"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

# Large Language Model Configuration
llm:
  provider: "openai"  # openai, huggingface, local
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 2000
  timeout: 30

# Vector Database Configuration
vector_db:
  type: "chromadb"  # chromadb, pinecone, faiss
  persist_directory: "./chroma_db"
  collection_name: "nuclei_templates"
  embedding_model: "text-embedding-ada-002"
  chunk_size: 1000
  chunk_overlap: 200

# Nuclei Configuration
nuclei:
  binary_path: "nuclei"  # Path to nuclei binary
  timeout: 30
  validate_args:
    - "--validate"
    - "--verbose"
  templates_dir: "./rag_data/nuclei-templates"

# RAG Configuration
rag:
  max_retrieved_docs: 5
  similarity_threshold: 0.7
  search_type: "similarity"  # similarity, mmr
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "file"
      filename: "logs/app.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
    - type: "console"

# Security Configuration
security:
  rate_limit:
    requests_per_minute: 60
    burst_size: 10
  input_validation:
    max_prompt_length: 1000
    allowed_file_types: [".yaml", ".yml"]
  
# Performance Configuration
performance:
  max_concurrent_requests: 10
  request_timeout: 120
  cache_ttl: 3600  # 1 hour

# Template Generation Configuration
template_generation:
  max_retries: 3
  validation_required: true
  output_format: "yaml"
  include_metadata: true
