# Secrets configuration file - DO NOT COMMIT TO GIT
# Copy this file from secrets.example.yaml and fill in your actual values
openai_api_key: "your-openai-api-key-here"
gemini_api_key: "your-gemini-api-key-here"
# set OPENAI_API_KEY=your-openai-api-key-here
# echo %OPENAI_API_KEY%

openai:
  api_key: "your-openai-api-key-here"
  organization: "your-openai-organization-here"

gemini:
  api_key: "your-gemini-api-key-here"
  model: "your-gemini-model-here"

vector_db:
  # For Pinecone
  pinecone_api_key: "your-pinecone-api-key-here"
  pinecone_environment: "your-pinecone-environment"

  # For other vector databases
  connection_string: "your-vector-db-connection-string"

# Additional API keys
external_apis:
  shodan_api_key: "your-shodan-api-key" # Optional for enrichment
  github_token: "your-github-token" # Optional for template updates

# Database credentials (if using external DB for logging/analytics)
database:
  host: "localhost"
  port: 5432
  username: "nuclei_agent"
  password: "your-database-password"
  database: "nuclei_agent_db"

# Security keys
security:
  jwt_secret: "your-jwt-secret-key-for-api-authentication"
  encryption_key: "your-32-character-encryption-key"
